# 指定 compose 文件版本，与 docker 兼容，高版本的 docker 一般使用 3.x。
version: '3.7'

services:
  # 设置服务名
  consul_server1:
    # 配置所使用的镜像
    image: consul
    # 容器总是重启
    restart: always
    # 容器名称
    container_name: consul_server1
    #与宿主机的端口映射
    ports:
      - 8500:8500
      - 8300:8300
      - 8301:8301
      - 8302:8302
      - 8600:8600
    #容器目录映射
    volumes:
      - /usr/mydata/consul/consul_server1/data:/consul/data
      - /usr/mydata/consul/consul_server1/config:/consul/config
    # 覆盖容器默认启动命令
    command: agent -server -bind=0.0.0.0 -client=0.0.0.0 -bootstrap-expect=1 -ui -node=consul_server1