# 指定 compose 文件版本，与 docker 兼容，高版本的 docker 一般使用 3.x。
version: '3.7'

services:
  # 设置服务名
  zookeeper_service2:
    # 配置所使用的镜像
    image: zookeeper
    # 容器总是重启
    restart: always
    # 容器名称
    container_name: zookeeper_service2
    #与宿主机的端口映射
    ports:
      - 2182:2181
    #容器目录映射
    volumes:
      - /usr/mydata/zookeeper/zookeeper_service2/data:/data
      - /usr/mydata/zookeeper/zookeeper_service2/datalog:/datalog
    # 设置环境变量
    environment:
      # Server 唯一标识（1 - 255）
      ZOO_MY_ID: 2
      # 指定服务信息，格式： server.A=B:C:D;E
      # 其中： A 表示服务器标识，B 是服务器 ip（服务名），C 是服务器与集群中 Leader 进行交互的端口，D 是用来选取新 Leader 进行交互的端口, E 为端口号
      ZOO_SERVERS: server.2=zookeeper_service2:2888:3888;2181 server.3=zookeeper_service3:2888:3888;2181 server.4=zookeeper_service4:2888:3888;2181

  # 设置服务名
  zookeeper_service3:
    # 配置所使用的镜像
    image: zookeeper
    # 容器总是重启
    restart: always
    # 容器名称
    container_name: zookeeper_service3
    #与宿主机的端口映射
    ports:
      - 2183:2181
    #容器目录映射
    volumes:
      - /usr/mydata/zookeeper/zookeeper_service3/data:/data
      - /usr/mydata/zookeeper/zookeeper_service3/datalog:/datalog
    # 设置环境变量
    environment:
      # Server 唯一标识（自然数）
      ZOO_MY_ID: 3
      # 指定服务信息，格式： server.A=B:C:D;E
      # 其中： A 表示服务器标识，B 是服务器 ip（服务名），C 是服务器与集群中 Leader 进行交互的端口，D 是用来选取新 Leader 进行交互的端口, E 为端口号
      ZOO_SERVERS: server.2=zookeeper_service2:2888:3888;2181 server.3=zookeeper_service3:2888:3888;2181 server.4=zookeeper_service4:2888:3888;2181

  # 设置服务名
  zookeeper_service4:
    # 配置所使用的镜像
    image: zookeeper
    # 容器总是重启
    restart: always
    # 容器名称
    container_name: zookeeper_service4
    #与宿主机的端口映射
    ports:
      - 2184:2181
    #容器目录映射
    volumes:
      - /usr/mydata/zookeeper/zookeeper_service4/data:/data
      - /usr/mydata/zookeeper/zookeeper_service4/datalog:/datalog
    # 设置环境变量
    environment:
      # Server 唯一标识（自然数）
      ZOO_MY_ID: 4
      # 指定服务信息，格式： server.A=B:C:D;E
      # 其中： A 表示服务器标识，B 是服务器 ip（服务名），C 是服务器与集群中 Leader 进行交互的端口，D 是用来选取新 Leader 进行交互的端口, E 为端口号
      ZOO_SERVERS: server.2=zookeeper_service2:2888:3888;2181 server.3=zookeeper_service3:2888:3888;2181 server.4=zookeeper_service4:2888:3888;2181